[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "graphed_checkers_SALSAPACKET"
dynamic = ["version"]
description = 'Playing with graphs, so I decided to make a game of checkers! Also an experiment to learn packaging.'
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
keywords = []
authors = [
  { name = "salsapacket", email = "info@salsapacket.com" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = []

[project.urls]
Documentation = "https://github.com/avallente/graphed-checkers#readme"
Issues = "https://github.com/avallente/graphed-checkers/issues"
Source = "https://github.com/avallente/graphed-checkers"

[tool.hatch.version]
path = "src/graphed_checkers/__about__.py"

[tool.hatch.envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/graphed_checkers tests}"

[tool.coverage.run]
source_pkgs = ["graphed_checkers", "tests"]
branch = true
parallel = true
omit = [
  "src/graphed_checkers/__about__.py",
]

[tool.coverage.paths]
graphed_checkers = ["src/graphed_checkers", "*/graphed-checkers/src/graphed_checkers"]
tests = ["tests", "*/graphed-checkers/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]

[tool.hatch.build.targets.wheel]
packages = ["src/graphed_checkers"]